[project]
name = "dalf"
version = "0.0.0"
authors = [
    { name="Uğur Özyılmazel", email="ugurozyilmazel@gmail.com" },
]
description = "Django admin list filter with goodies"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django :: 5.0",
    "Development Status :: 3 - Alpha",
]

# [project.urls]
# Homepage = ""
# Issues = ""
